GLKTERM_VERSION = main
GLKTERM_BRANCH = main
GLKTERM_SOURCE = $(GLKTERM_BRANCH).tar.gz
GLKTERM_SITE = https://github.com/benklop/glkterm/archive/refs/heads
GLKTERM_LICENSE = MIT
GLKTERM_LICENSE_FILES = LICENSE
GLKTERM_DEPENDENCIES = host-pkgconf host-cmake ncurses zlib \
    sdl2 sdl2_mixer

GLKTERM_CONF_OPTS = \
	-DWITH_ADVSYS=$(if $(BR2_PACKAGE_GLKTERM_ADVSYS),ON,OFF) \
	-DWITH_AGILITY=$(if $(BR2_PACKAGE_GLKTERM_AGILITY),ON,OFF) \
	-DWITH_ALAN2=$(if $(BR2_PACKAGE_GLKTERM_ALAN2),ON,OFF) \
	-DWITH_ALAN3=$(if $(BR2_PACKAGE_GLKTERM_ALAN3),ON,OFF) \
	-DWITH_BOCFEL=$(if $(BR2_PACKAGE_GLKTERM_BOCFEL),ON,OFF) \
	-DWITH_GLULXE=$(if $(BR2_PACKAGE_GLKTERM_GLULXE),ON,OFF) \
	-DWITH_GIT=$(if $(BR2_PACKAGE_GLKTERM_GIT),ON,OFF) \
	-DWITH_HUGO=$(if $(BR2_PACKAGE_GLKTERM_HUGO),ON,OFF) \
	-DWITH_JACL=$(if $(BR2_PACKAGE_GLKTERM_JACL),ON,OFF) \
	-DWITH_LEVEL9=$(if $(BR2_PACKAGE_GLKTERM_LEVEL9),ON,OFF) \
	-DWITH_MAGNETIC=$(if $(BR2_PACKAGE_GLKTERM_MAGNETIC),ON,OFF) \
	-DWITH_PLUS=$(if $(BR2_PACKAGE_GLKTERM_PLUS),ON,OFF) \
	-DWITH_SCARE=$(if $(BR2_PACKAGE_GLKTERM_SCARE),ON,OFF) \
	-DWITH_SCOTT=$(if $(BR2_PACKAGE_GLKTERM_SCOTT),ON,OFF) \
	-DWITH_TADS=$(if $(BR2_PACKAGE_GLKTERM_TADS),ON,OFF) \
	-DWITH_TAYLOR=$(if $(BR2_PACKAGE_GLKTERM_TAYLOR),ON,OFF)

$(eval $(cmake-package))